### ISSUE TITLE
テスト用Issue

### ISSUE THREAD

**Issue by everystudio** [zackfair396/test#1]
Issueは目標なんかを作って、完了したらIssueごとにCloseして、タスク管理に使うことが出来ます。
主に他の人からプロジェクトの機能追加なんかを依頼されるときにIssueに要件などを書いてリンク共有されます。
プログラム実装が完了するとCloseして実装終了という感じで使い捨てるタイプです。

試しにこのIssueを確認したらCloseしてみてください。

**Comment by zackfair396** [comment]
確認しました。
ありがとうございます。
